<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CalculatorGUI</RootNamespace>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PublishSingleFile>True</PublishSingleFile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaCheckDiagnosticsConflict>false</AvaloniaCheckDiagnosticsConflict>
    <ApplicationIcon>Assets\CalcLogo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="ProDiagnostics" Version="12.1.0" />
  </ItemGroup>
</Project>
